[package]
name = "abi"
version = "0.1.0"
edition = "2021"
authors = ["Adhyan <adhyanpatel@gmail.com>"]

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.132"
